
package org.soa.soap.editor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DatabaseModificationException", targetNamespace = "http://soa.org/soap/editor")
public class DatabaseModificationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatabaseModificationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatabaseModificationException_Exception(String message, DatabaseModificationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatabaseModificationException_Exception(String message, DatabaseModificationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.soa.soap.editor.DatabaseModificationException
     */
    public DatabaseModificationException getFaultInfo() {
        return faultInfo;
    }

}
