
package org.soa.soap.editor;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EditorService", targetNamespace = "http://soa.org/soap/editor")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EditorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ElementNotFoundException_Exception
     * @throws DatabaseModificationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateElementFortune", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.UpdateElementFortune")
    @ResponseWrapper(localName = "updateElementFortuneResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.UpdateElementFortuneResponse")
    public void updateElementFortune(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws DatabaseModificationException_Exception, ElementNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws DatabaseModificationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addCategory", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.AddCategory")
    @ResponseWrapper(localName = "addCategoryResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.AddCategoryResponse")
    public void addCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws DatabaseModificationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.soa.soap.editor.CategoryDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCategories", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.GetAllCategories")
    @ResponseWrapper(localName = "getAllCategoriesResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.GetAllCategoriesResponse")
    public List<CategoryDTO> getAllCategories();

    /**
     * 
     * @return
     *     returns java.util.List<org.soa.soap.editor.CategoryDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCategoriesForSoapUser", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.GetAllCategoriesForSoapUser")
    @ResponseWrapper(localName = "getAllCategoriesForSoapUserResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.GetAllCategoriesForSoapUserResponse")
    public List<CategoryDTO> getAllCategoriesForSoapUser();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws DatabaseModificationException_Exception
     * @throws CategoryNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addElement", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.AddElement")
    @ResponseWrapper(localName = "addElementResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.AddElementResponse")
    public void addElement(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Integer arg4)
        throws CategoryNotFoundException_Exception, DatabaseModificationException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ElementNotFoundException_Exception
     * @throws DatabaseModificationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateElementPower", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.UpdateElementPower")
    @ResponseWrapper(localName = "updateElementPowerResponse", targetNamespace = "http://soa.org/soap/editor", className = "org.soa.soap.editor.UpdateElementPowerResponse")
    public void updateElementPower(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0)
        throws DatabaseModificationException_Exception, ElementNotFoundException_Exception
    ;

}
